### ISSUE TITLE
review comments

### ISSUE THREAD

**Issue by jrgm** [mozilla-services/switchboard-server#1]
Hi Miles. Here are some general comments:
- every file must start with a short MPL header, e.g.,
  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/index.js#L1-L3
- I'm not convinced using babel here provides much. Nodejs 4.x in strict mode
  supports `let`, `const` and `class`. `import` really provides nothing that
  `require` does not. Okay, default parameters are not available, which makes
  me sad, but can live without them.
- We discussed using Hapi. I'd be hapi-er if we use Hapi as the web framework,
  but we do use expressjs in the fxa-content-server, although that's not
  really an api server.
- should use `mozlog` (https://github.com/mozilla/mozlog) to be consistent
  with our other projects and with the Heka log processing pipeline in
  production. Don't make whd come after you when he needs to write a custom
  parser for your project.
- set up a coverage tool to produce a result from tests

Style:
- Mixed camelCase and snake_case identifiers. Pick one, your choice, as long
  as it's camelCase.
- 2 spaces, not 4. And never tabs.
- no working eslint (npm lint fails to run)
- if/else statements should use braces '{}'.
- testing for 'typeof not undefined' is usually not required; just check `if
  (!foo) { ...`.

I'm still not sure what this thing does, and haven't really poked at running it yet.

**Comment by milescrabill** [comment]
Most of these issues were fixed between ab113d14a1750c2ae69df0368f9ab7457ec50676 and ba1528e6c1f94265af0e35c02f972c88527e5c35, with some notable deviations.
- expressjs is still around
- I'm still using Babel, but the "require hook" method shouldn't have much of a speed consequence
- `typeof x != 'undefined'` works better logically in some places and seems to be "more correct" than `!foo`
- I'm using `x.hasOwnProperty(y)` in some other places instead of undefined checks

I started setting up Istanbul for coverage testing. Current report:
- 69.36% Statements (120/173)
- 50% Branches (45/90)
- 53.13% Functions (17/32)
- 63.91% Lines (85/133)
- 5 statements, 1 function, 12 branches Ignored

**TODO: better test coverage**
